### ISSUE TITLE
standalone empress tree-plot generates html that get stuck in loading screen

### ISSUE THREAD

**Issue by YasinEl** [biocore/empress#561] opened 2024-08-01 21:56 UTC
Hello,

I have installed the standalone empress distribution. After running 

`empress tree-plot --tree nf_output/treeGraph_6356_53477895.nw -fm nf_output/treeAnnotation_6356_53477895.tsv -o LacCer_34_1_O2`

I get:

[LacCer_34_1_O2.zip](https://github.com/user-attachments/files/16462179/LacCer_34_1_O2.zip)

However, when opening the html it never stops loading. 

I am on Ubuntu 20.04.6 LTS

**Comment by fedarko** [comment] 2024-08-02 05:21
Thanks for reporting this. I did some digging, and was not able to reproduce the problem. Would you mind sharing the following?

- Your original tree and feature metadata files
- The output of running `pip list` (you can run `pip list > piplist.txt` and upload that, if that's easier)
- The output of running `conda list`, if you are using conda

Tentatively, I suspect that something is going wrong with your installations of `numpy` and/or `iow`. I wonder if you have numpy 2 installed -- if so, maybe try downgrading (using e.g. `pip install "numpy<2"`), then recreating the visualization; this might fix the problem?

## Details on what's going wrong

From looking at the visualization ZIP file you shared (thank you!), it looks like the balanced parentheses representation of your tree is malformed. (This is the cause for the visualization remaining stuck at the loading screen: Empress' javascript code hits an error when reading this information during loading.)

The specific error occurs on line 723 in the `empress.html` file. This line should contain a balanced parentheses representation of your tree (in the form of a list of 51-bit integers); however, in your HTML file, the numbers are:

1. Wrapped by the term `np.uint8()`, for some reason

2. Very tiny (these numbers should be on the order of `2**51`, but they're all less than 1,000 -- suspiciously, the biggest of them is exactly `255`).

![image](https://github.com/user-attachments/assets/a5d105d4-55ce-4940-bc79-8c3cf797de3c)

## Tentative guess of the cause of the problem

It looks like what's happening is:

1. `iow` loads the tree using [`parse_newick()`](https://github.com/biocore/improved-octo-waddle/blob/6df7c5c8e1e9bb319e26e3801c41607fec4958da/bp/_io.pyx#L141), and treats each of the bits (0s and 1s) as `np.uint8` objects.
2. Empress [converts the iow tree to a list of 51-bit integers](https://github.com/biocore/empress/blob/cc3975a71c931f2d356856fb5ee9669b3f83f150/empress/core.py#L364) using its [`shifting()`](https://github.com/biocore/empress/blob/cc3975a71c931f2d356856fb5ee9669b3f83f150/empress/tools.py#L342-L407) function.
3. The elements in the output list retain the `np.uint8` type. Since they retain this type, they are all constrained to being ≤ 255, which results in this function outputting a malformed representation of the tree's structure.

Assuming that this is the cause of the problem, I think the problem should be fixed by modifying Empress' `shifting()` function to cast all bits to `int`s. A workaround would be capping numpy's version to < 2, if that is what's causing the bits to be `np.uint8`s and not just ints.

Copying @kwcantrell and @wasade.

**Comment by YasinEl** [comment] 2024-08-02 15:50
Thank you for the fast response and explanations! installing a "numpy<2" indeed solved the problem. 

Anyway here are the requested files in case it helps to fix something:

[treeFiles_and_condaList.zip](https://github.com/user-attachments/files/16472548/treeFiles_and_condaList.zip)

**Comment by fedarko** [comment] 2024-08-03 00:28
Perfect, glad that fixed things!

**Closed as completed by fedarko** 2024-08-03 00:28 UTC
Labels: bug, user support
