### ISSUE TITLE
Remove "hide non sample features" checkbox

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#182] opened 2020-06-18 04:46 UTC
1. Before doing any coloring/etc.:

![image](https://user-images.githubusercontent.com/4177727/84979245-d96bb200-b0e3-11ea-9211-de003e7020d2.png)

2. After checking the checkbox:

![image](https://user-images.githubusercontent.com/4177727/84979207-bccf7a00-b0e3-11ea-9c54-a862db1a70d0.png)

3. After pressing "update" to color nodes by body-site:

![image](https://user-images.githubusercontent.com/4177727/84979218-c35df180-b0e3-11ea-954a-c200e51247ab.png)

Interestingly, at this point, checking / unchecking the box doesn't seem to do anything.

Screenshots taken on the moving pictures tree, visualized using the current master branch as of writing.

**Comment by kwcantrell** [comment] 2020-06-18 05:03
That is the intended behavior (well maybe not the second one, the check box is only supposed to be available after the tree is colored). The idea was to hide all branches that were not colored so that you can better see what is colored. The current behavior is to hide all uncolored tips and internal nodes whose children aren't colored. I guess the name is a bit miss leading. Perhaps were should either rename the checkbox or change the behavior so and just hide the tips that are not observed in a sample (I think the second option might be better).

**Comment by kwcantrell** [comment] 2020-07-14 16:14
will be resolved with #101

**Comment by ElDeveloper** [comment] 2020-08-04 18:07
Closed as part of #277

**Closed by ElDeveloper** 2020-08-04 18:07 UTC
Labels: bug, good first issue
