### ISSUE TITLE
Biplot error: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by mestaki** [biocore/empress#289] opened 2020-07-31 23:11 UTC
Q2 2020.6
empress                   0.2.0.dev0               pypi_0    pypi (installed July 31)

Download the Moving Pictures tutorial files:
```bash
wget https://docs.qiime2.org/2020.6/data/tutorials/moving-pictures/table.qza
wget https://data.qiime2.org/2020.6/tutorials/moving-pictures/sample_metadata.tsv
wget https://docs.qiime2.org/2020.6/data/tutorials/moving-pictures/rooted-tree.qza
wget https://docs.qiime2.org/2020.6/data/tutorials/moving-pictures/taxonomy.qza
wget  https://docs.qiime2.org/2020.6/data/tutorials/moving-pictures/core-metrics-results/unweighted_unifrac_pcoa_results.qza
wget https://raw.githubusercontent.com/biocore/empress/master/docs/moving-pictures/biplot.qza
```

The stand alone Empress, and Empire plot work fine, but when I try to load the biplot I get the following error:
```bash
qiime empress plot \
    --i-tree rooted-tree.qza \
    --i-pcoa biplot.qza \
    --i-feature-table table.qza \
    --m-sample-metadata-file sample_metadata.tsv \
    --m-feature-metadata-file taxonomy.qza \
    --p-filter-extra-samples \
    --p-number-of-features 10 \
    --o-visualization empire-biplot.qzv
```

> Traceback (most recent call last):
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/q2cli/commands.py", line 329, in __call__
>     results = action(**arguments)
>   File "<decorator-gen-554>", line 2, in plot
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
>     output_types, provenance)
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/qiime2/sdk/action.py", line 452, in _callable_executor_
>     ret_val = self._callable(output_dir=temp_dir, **view_args)
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/empress/_plot.py", line 42, in plot
>     feats['importance'] = feats.apply(euclidean, axis=1, args=(origin,))
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/frame.py", line 6928, in apply
>     return op.get_result()
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/apply.py", line 186, in get_result
>     return self.apply_standard()
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/apply.py", line 292, in apply_standard
>     self.apply_series_generator()
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
>     results[i] = self.f(v)
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/apply.py", line 112, in f
>     return func(x, *args, **kwds)
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/scipy/spatial/distance.py", line 620, in euclidean
>     return minkowski(u, v, p=2, w=w)
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/scipy/spatial/distance.py", line 523, in minkowski
>     dist = norm(u_v, ord=p)
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/scipy/linalg/misc.py", line 142, in norm
>     a = np.asarray_chkfinite(a)
>   File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/numpy/lib/function_base.py", line 499, in asarray_chkfinite
>     "array must not contain infs or NaNs")
> ValueError: ('array must not contain infs or NaNs', 'occurred at index 4b5eeb300368260019c1fbc7a3c718fc')
> 

Note that the 4b5eeb300368260019c1fbc7a3c718fc feature is the most abundant feature from the table and appears at the top, so it is likely that this error is being raised on this feature because it is encountering it first.  
I've tried artifacts made using q2-2019.10 as well with the same error.

**Comment by kwcantrell** [comment] 2020-07-31 23:17
Hey @mestaki, I believe this is caused by #287 

This is fixed in #288. You can pull the development branch:

```
git checkout -b kwcantrell-fix-287 master
git pull https://github.com/kwcantrell/empress.git fix-287
```

**Comment by fedarko** [comment] 2020-08-01 00:53
Wait, will #288 will fix this? This looks like it's a python error in matching the biplot features to the tree/table, and #288's changes are all in the JavaScript code. Sorry if I'm missing something.

**Comment by kwcantrell** [comment] 2020-08-01 01:07
I guess there could be an error on the Python side of things. TBH I did not check. However, this error is caused because, when clicking on a tip or arrow, we are sending the feature id instead of sample ids to Emperor. Here is a screen shot of the error when clicking on a arrow in the biplot:

![error](https://user-images.githubusercontent.com/28127694/89090449-d3f6be00-d357-11ea-97b9-857401551134.png)

As you can see Emperor is throwing an error because it is trying to highlight 1d2ef... which does not exist since it is a a feature id  and not a sample id.
 
Currently, in select-node-menu, we are sending the result of biom.getObsIDsIntersection() (which returns feature ids) to Emperor. #288 fixes this because it returns the result of  biom.getSamplesByObservations() (which returns sample ids) to Emperor.

**Comment by kwcantrell** [comment] 2020-08-01 01:15
Oh wait, disregard my previous two comments. I wasn't paying to much attention to the stack trace @mestaki posted. I saw the title and remembered getting a similar error yesterday and assumed it was the something. @fedarko you are right, this looks like it originates on the python side of things when the .qzv file is being created.

**Comment by fedarko** [comment] 2020-08-01 01:34
No worries! It's true that, even if this plot would get created successfully, it'd still have the problem documented in #287 -- so both errors are relevant :)

I think I know the cause of this error -- TLDR, I believe it's due to an old version of Empress being used.

It looks like the particular line that's giving us problems in the stack trace is [this one](https://github.com/biocore/empress/blob/dfcd8ba75eff2219066356875080b03e21042ae7/empress/_plot.py#L45):

```
File "/home/mestaki/miniconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/empress/_plot.py", line 42, in plot
feats['importance'] = feats.apply(euclidean, axis=1, args=(origin,))
```

... which is just trying to figure out the magnitudes of each of the features in the biplot, so Empress can filter down to just the most "important" features (10, in this case). It looks like @ElDeveloper recently fixed a corner-case in this code block that replaced NaN values with 0s (see the changes in `_plot.py` [here](https://github.com/biocore/empress/pull/270/files)). It would make sense that this is the problem causing this error, since the error message involves complaining about Infinities/NaNs.

I know it's weird that this is the problem, since @mestaki just re-installed Empress today going by the original post. However -- I don't think the reinstall worked. This is because in the current version of Empress on the master branch, this line (`feats['importance'] = ...`) is line 45. In @mestaki's traceback, this same line is on line 42. Yoshiki's [changes that fixed this bug](https://github.com/biocore/empress/pull/270/files) took up exactly 3 lines -- so it seems reasonable to conclude that @mestaki's version of Empress __is not the most recent version of Empress__, and instead a (slightly) older version that does not have Yoshiki's changes.

So now, all that's left is figuring out _why_ the Empress reinstall didn't work. Maybe removing Empress with `pip uninstall empress` then re-installing it with `pip install git+...` would work?

**Comment by kwcantrell** [comment] 2020-08-01 01:40
@fedarko that makes sense.

It could also be an old version of Empress is cached in @mestaki qiime2 environment. Might be worthwhile to also run the following command in the main folder of Empress (i.e. the one that contains setup.py):

`pip install -e . && qiime dev refresh-cache`

**Comment by mestaki** [comment] 2020-08-01 01:43
Thanks for the quick replies on this @fedarko and @kwcantrell.
Sure enough, pip uninstalling and reinstalling solved the problem. Weird, because I definitely ran the `pip install git+https://github.com/biocore/empress.git` and it showed it successfully installing. I did have the previous empress installed in my conda env but I always assumed the reinstalling would override the existing version (this certainly has been the case with empress too). But who knows. Code ghouls?
Either way, this looks like a fixed and closed issue to me!

**Comment by fedarko** [comment] 2020-08-01 01:48
Sweet, thanks Kalen and Bod! Closing this now.

Not to be a pain, but @mestaki I think you might need to uninstall + reinstall one more time -- @kwcantrell just added in a fix for another related problem which was messing up the node selection UI.

**Closed by fedarko** 2020-08-01 01:48 UTC
