### ISSUE TITLE
Profiling Empress

### ISSUE THREAD

**Issue by fedarko** [biocore/empress#151] opened 2020-04-01 01:09 UTC
Both the Python and JS halves, ideally. This relates to #74, and some comments that came up in #145 ([1](https://github.com/biocore/empress/pull/145#discussion_r399712873), [2](https://github.com/biocore/empress/pull/145#discussion_r401169166), maybe more that I'm missing).

Using the large tree @antgonza kindly provided in #74, this would let us get a sense for where the "pain points" are currently (and where would be best to spend time optimizing). I imagine we'll need to focus on reducing memory usage in the JS side of things, since it's clear that huge enough trees will just break web browsers as is. (This could be doable using something like web workers to retrieve only subsets of the tree, but that's an idea for another issue.)

**Comment by fedarko** [comment] 2020-04-20 18:54
Also, something I noticed in #157 is that for some reason large trees load a lot faster in Firefox than in Chromium (... at least for the specific versions on my computer). It would be good to isolate the reason why, since this could indicate places to improve performance.

**Comment by antgonza** [comment] 2020-06-13 13:07
Hi @fedarko, just wondering if this is a duplicate of https://github.com/biocore/empress/issues/74 ?

**Comment by fedarko** [comment] 2020-06-14 01:55
These are closely related issues, but I initially thought of them as separate things -- to me, #74 is about being able to say "on a tree with [1K / 10K / 100K / 1M / ...] tips, here's how well Empress performs...", and this issue is more about finding the bottlenecks in Empress' code (e.g. how fast each layout algorithm is, or how much time we lose by using skbio.TreeNode instead of the balanced parentheses implementation).

That said, after writing that out I suppose that these are really similar concerns. I'm ok with renaming / merging this issue into #74 if you'd like.

**Comment by antgonza** [comment] 2020-06-14 13:18
Thank you for the explanation @fedarko. I think both can stay opened and deal with them independently.

**Comment by fedarko** [comment] 2020-08-10 20:53
The easiest way to do this would probably just be inserting a bunch of print / console.log statements (e.g. "starting circular layout at time [ ]", "finished circular layout at time [ ]") throughout the code, and seeing where the most time is taken. I'm sure more sophisticated solutions would also work well.

From conversation with @ElDeveloper, it sounds like the main thing we need is a sense of where the bottlenecks in the code are. These are likely the layout algorithms, but there may be unexpected slow places as well.

It'd also be nice to see what tasks are delaying the initial display / rendering of the tree in the JS code. For ~200k-tip trees, there's a noticeable lag between opening up the QZV and seeing the tree for the first time; decreasing this lag would be good.

**Comment by ElDeveloper** [comment] 2020-08-31 20:30
Since this issue refers to a high level "finding bottlenecks" item, I would prefer that we instead focus on addressing the things we have now identified and documented (everything tagged as [performance](https://github.com/biocore/empress/labels/performance)). Regardless, for #74 we should still profile how does the application perform with different dataset sizes, etc.

**Closed by ElDeveloper** 2020-08-31 20:30 UTC
Labels: performance
